apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.nameOverride }}
spec:
  secretName: {{ printf "%v%v" .Values.nameOverride "-tls" }}
  privateKey:
    rotationPolicy: Always
  commonName: {{ printf "%s.%s.%s" .Values.nameOverride .Values.cloud.region "cloudapp.azure.com" }}
  dnsNames:
    - {{ printf "%s.%s.%s" .Values.nameOverride .Values.cloud.region "cloudapp.azure.com" }}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer