apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-chart.fullname" . }}
  labels:
    {{- include "application-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "application-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.nameOverride }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.applicationSecrets .Values.applicationVariables }}
          env:
          {{- if .Values.applicationSecrets }}
          {{- range $key, $val := .Values.applicationSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.nameOverride }}
                key: {{ $key }}
          {{- end }}
          {{- end }}
          {{- if .Values.applicationVariables }}
          {{- range $key, $val := .Values.applicationVariables }}
          - name: {{ $key }}
            valueFrom:
              configMapKeyRef:
                name: {{ $.Values.nameOverride }}
                key: {{ $key }}
          {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            {{ if .Values.service.targetPort }}
            - name: app
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- end }}
            {{- range .Values.service.additionalPorts }}
            - name: {{ .portName }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tls
              mountPath: "/etc/ssl/nginx"
              readOnly: true
            {{- with .Values.volumes }}
              - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
          {{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ printf "%s-%s" .Values.nameOverride "tls" }}
      {{- with .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
