{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.nameOverride -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "application-chart.labels" . | nindent 4 }}
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: {{ default "/" .Values.ingress.pathPrefix }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ default "azure-application-gateway" .Values.ingress.className }}
  {{- end }}
  {{- if .Values.certificate.enabled }}
  tls:
    - hosts:
      {{- if eq "ClusterIP" .Values.service.type }}
        - {{ printf "%s.%s.%s" .Values.nameOverride .Values.organizationIdentifier "solvddev.com" }}
      {{- else }}
        - {{ printf "%s.%s.%s" .Values.nameOverride .Values.cluster.region "cloudapp.azure.com" }}
      {{- end }}
      secretName: {{ printf "%v%v" .Values.nameOverride "-tls" }}
  {{- end }}
  rules:   
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
    {{- else }}
    {{- if eq "ClusterIP" .Values.service.type }}
    - host: {{ printf "%s.%s.%s" .Values.nameOverride .Values.organizationIdentifier "solvddev.com" }}
    {{- else }}
    - host: {{ printf "%s.%s.%s" .Values.nameOverride .Values.cluster.region "cloudapp.azure.com" }}
    {{- end }}
    {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ default "ImplementationSpecific" .Values.ingress.pathType }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                {{- if .Values.certificate.enabled }}
                  number: 443
                {{- else }}
                  number: {{ $svcPort }}
                {{- end }}
              {{- else }}
              serviceName: {{ $fullName }}
                {{- if .Values.certificate.enabled }}
                servicePort: 443
                {{- else }}
                servicePort: {{ $svcPort }}
                {{- end }}
              {{- end }}
{{- end -}}
