{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .name }}
spec:
  accessModes:
  - {{ default "ReadWriteOnce" .accessMode }}
  storageClassName: {{ default "managed-csi" .storageClassName }}
  resources:
    requests:
      storage: {{ default "1Gi" .storage }}
{{- end }}
