apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "application-chart.labels" . | nindent 4 }}
  {{- if eq "LoadBalancer" .Values.service.type }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.nameOverride }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "application-chart.selectorLabels" . | nindent 4 }}
